/*******************************************************************************
 * DEMO PROJECT: sfe-simple-stream | Script: Complete Teardown
 * ⚠️ DESTRUCTIVE OPERATION - ALL DATA WILL BE PERMANENTLY DELETED
 * PURPOSE: Remove all demo objects while preserving SNOWFLAKE_EXAMPLE database.
 * CLEANUP RULE: Drop schemas, tables, streams, tasks, pipes, secrets, repo, warehouse, API integration.
 ******************************************************************************/

USE ROLE SYSADMIN;
USE DATABASE SNOWFLAKE_EXAMPLE;

ALTER TASK IF EXISTS STAGING_LAYER.sfe_staging_to_analytics_task SUSPEND;
ALTER TASK IF EXISTS RAW_INGESTION.sfe_raw_to_staging_task SUSPEND;
CALL SYSTEM$WAIT(5);

DROP TASK IF EXISTS STAGING_LAYER.sfe_staging_to_analytics_task;
DROP TASK IF EXISTS RAW_INGESTION.sfe_raw_to_staging_task;
DROP STREAM IF EXISTS RAW_INGESTION.sfe_badge_events_stream;
DROP STREAM IF EXISTS STAGING_LAYER.stg_badge_events_stream;
DROP PIPE IF EXISTS RAW_INGESTION.sfe_badge_events_pipe;
DROP PROCEDURE IF EXISTS STAGING_LAYER.sfe_process_badge_events();
DROP PROCEDURE IF EXISTS DEMO_REPO.SFE_DEPLOY_PIPELINE();
DROP PROCEDURE IF EXISTS DEMO_REPO.SFE_VALIDATE_PIPELINE();
DROP PROCEDURE IF EXISTS DEMO_REPO.SFE_RESET_PIPELINE();

DROP VIEW IF EXISTS RAW_INGESTION.V_CHANNEL_STATUS;
DROP VIEW IF EXISTS RAW_INGESTION.V_INGESTION_METRICS;
DROP VIEW IF EXISTS RAW_INGESTION.V_END_TO_END_LATENCY;
DROP VIEW IF EXISTS RAW_INGESTION.V_DATA_FRESHNESS;
DROP VIEW IF EXISTS RAW_INGESTION.V_PARTITION_EFFICIENCY;
DROP VIEW IF EXISTS RAW_INGESTION.V_STREAMING_COSTS;
DROP VIEW IF EXISTS RAW_INGESTION.V_TASK_EXECUTION_HISTORY;
DROP VIEW IF EXISTS RAW_INGESTION.V_DATA_QUALITY_SUMMARY;

DROP TABLE IF EXISTS ANALYTICS_LAYER.FCT_ACCESS_EVENTS;
DROP TABLE IF EXISTS ANALYTICS_LAYER.DIM_USERS;
DROP TABLE IF EXISTS ANALYTICS_LAYER.DIM_ZONES;
DROP TABLE IF EXISTS ANALYTICS_LAYER.DIM_READERS;
DROP TABLE IF EXISTS STAGING_LAYER.STG_BADGE_EVENTS;
DROP TABLE IF EXISTS RAW_INGESTION.RAW_BADGE_EVENTS;

DROP SCHEMA IF EXISTS ANALYTICS_LAYER;
DROP SCHEMA IF EXISTS STAGING_LAYER;
DROP SCHEMA IF EXISTS RAW_INGESTION;

USE ROLE ACCOUNTADMIN;

DROP SECRET IF EXISTS DEMO_REPO.SFE_SS_ACCOUNT;
DROP SECRET IF EXISTS DEMO_REPO.SFE_SS_USER;
DROP SECRET IF EXISTS DEMO_REPO.SFE_SS_JWT_KEY;
DROP GIT REPOSITORY IF EXISTS DEMO_REPO.sfe_simple_stream_repo;
DROP SCHEMA IF EXISTS DEMO_REPO;
DROP WAREHOUSE IF EXISTS SFE_SIMPLE_STREAM_WH;
DROP API INTEGRATION IF EXISTS SFE_GIT_API_INTEGRATION;
